### ISSUE TITLE
Missing Questions after 2477

### ISSUE THREAD

**Issue by Zackhardtoname** [adixmr/leetcode#2]
Currently there are 2577 questions, but the CSV contains only 2400 questions.

**Comment by adixmr** [comment]
When I started the project, leetcode probably had 2100-2200 questions and I had put a limit of 2400 for scraping that's why it does not fetch after that count. I have just increased the limit to 3000 and now we should be good for this year.

Soon, I'll use a dynamic approach so that we don't have to set a number manually.

**Comment by Zackhardtoname** [comment]
awesome!
